name: grid-ar
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - numpy=1.15.0
  - python=3.6
  - pip=20.1.1
  - pip:
    - pandas==0.24.1
    - torch==1.0.1.post2
    - torchvision==0.2.1
    - scipy==1.2.0
    - multiprocess==0.70.12
    - scikit-learn==0.24.2
    - fitter==1.5.2
    - numexpr==2.7.1